stages:
  - build

before_script:
  # auth docker registry before using it
  - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$KSZK_NEXUS_USERNAME\",\"password\":\"$KSZK_NEXUS_PASSWORD\"}}}"
    > /kaniko/.docker/config.json

###################### Image builder template #####################

# hidden job, not gonna run, just for the inheritance
.image-template:
  stage: build
  variables:
    IMAGE_NAME: $CI_JOB_NAME
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $CI_PROJECT_DIR/Dockerfile
      --destination "$CI_REGISTRY_IMAGE/$IMAGE_NAME"

############################ Real work ############################

qt:
  extends: .image-template
